#ifndef ASCII_CLASH_AI_NAMES_H
#define ASCII_CLASH_AI_NAMES_H
#include <string>
#include <vector>
static inline const std::vector<std::string> TeamNames{
    "Big Baddies",
    "Team R",
    "FSTG",
    "The Grumbling Horde",
    "Snickers of DOOM",
    "Crusty Knuckles",
    "The Wet Socks",
    "Rabid Accountants",
    "Filthy Casuals",
    "The Unbothered",
    "Order of the Mariposa Lily",
    "Chaos Incorporated",
    "The Floor Gang",
    "Middling Menaces",
    "Villains™",
    "The Lurkers",
    "Absolute Units",
    "The Soggy Brigade",
    "Mediocre Mayhem",
    "Feral Management",
    "The Nuisance Collective",
    "FGSe",
    "The Reckless Few",
    "Unwashed Masses",
    "Insomniacs",
    "The Gravel Eaters",
    "Tacticool",
    "The Fumbling Five",
    "Aggressively Average Armpits",
    "The Suspicious Lot",
    "Trying our best",
    "Known Alcoholics",
    "Rogue Staplers",
    "Anonymous Alcoholics",
    "The Bludgeoning Mass",
    "Semi-Known Alcoholics",
    "Team Whoops",
    "The Chronic Underperformers",
    "The Rancid Few",
    "Shambling Wrecks",
    "Questionable Choices",
};

static inline const std::vector<std::string> MonNames{
    "Achim",
    "Murkk",
    "Gunnar",
    "Flunky",
    "Snitter",
    "Ikkit",
    "Franz",
    "Schmurbulock The Great",
    "Schmurbulock The Mediocre",
    "Schmurbulock Jr.",
    "Ms. Schmurbulock",
    "Mr. Schmurbulock",
    "Borble",
    "Grunsh",
    "Weeble",
    "Feddock",
    "Splunk",
    "Dorbius",
    "Krumple",
    "Snargus",
    "Blobwick",
    "Glumtor",
    "Nurgg",
    "Twonk",
    "Plifter Shop Lifter",
    "Skrunt",
    "Honkus Schmonkus",
    "Vektoooorrrr",
    "Gorbachev",
    "Gloopsies",
    "Swumbo",
    "Clonkbert",
    "Frogbert",
    "Shrobbins",
    "Muckle",
    "Grumf",
    "Snodwig",
    "Blortus",
    "Flibbage",
    "Wumbus",
    "Gretch",
    "Squelch",
    "Dinkbert",
    "Krabbish",
    "Glumwick",
    "Snerble",
    "Ponkus",
    "Zibble",
    "Torgle",
    "Blunko",
    "Skrumble",
    "Dorvish",
    "Frungle",
    "Groplick",
    "Sputwick",
    "Nurble",
    "Twigbert",
    "Brandon",
    "Slonk",
    "Perno",
    "Yhannique",
    "Drabnus",
    "Flumbert",
    "Grumple",
    "Snorvish",
    "Grunt",
    "Blegbert",
    "Squbble",
    "Maerz, Consumer of EGG",
    "Tronkus",
    "Glumble",
    "Andrea Murkel",
    "Rick Estliy",
    "Dribwick",
    "Flobbert",
    "[REDACTED]",
    "Krunchle",
    "Snoffle",
    "Blonkbert",
    "Spudwick",
    "Judgy Judge",
    "Twumble",
    "Clonkish",
    "Slorble",
    "Borkwick",
    "Heinrich The Unpleasant",
    "Lawyer",
    "Olaf The Dim",
    "Big Bad Bastard",
    "Andreas From Accounting",
    "Gwendolyn The Gross",
    "Reginald The Rat",
    "Tiny Tina",
    "Enormous Eduard",
    "Real Schmurbulock",
    "Settra, Great Kind, the Imperishable Buffer Overflow",
};


inline std::string GetRandomTeamName() { return TeamNames[rand() % TeamNames.size()]; }
inline std::string GetRandomMonName() { return MonNames[rand() % MonNames.size()]; }

#endif
